### ISSUE TITLE
Component badge

### ISSUE THREAD

**Issue by buschtoens** [ForbesLindesay-Unmaintained/component-website#9]
component/component#144

![This is a component](https://a248.e.akamai.net/camo.github.com/e6d07f3172a47e730812b02d9350c9f7b866fd11/687474703a2f2f3136352e3232352e3132392e3132383a353035302f636f6d706f6e656e742e706e67)

**Comment by buschtoens** [comment]
Waiting for TJ's ok on component/component#190.

**Comment by buschtoens** [comment]
![example](http://f.cl.ly/items/1z2l1M090y0y372o0F0G/test.svg)

Presumed TJ's ok. Finished [component-badge](https://github.com/silvinci/component-badge).

`npm install component-badge`

`badge([count, [scale]])` returns a String representing a SVG image.
`count` is the number show under the logo ("1337 available"). If left out the subline comletely vanishes.
`scale` is optional and is multiplied with the logos default width and height (480px x120px).

`badge.load(path)` loads a new template.
`path` is the path to the template to be loaded.

``` javascript
var badge = require("component-badge");

console.log(badge(1337, 1.5)); // <svg width="720px" height="180px">...

badge.load("./myNewLogo.svg");
```

---

Edit: Syntax obviously changed.

**Comment by ForbesLindesay** [comment]
Great stuff, if you want to integrate this with the main project I'll see about integrating it some time on Monday (UTC).

I've reserved the organisation name @refer so that the following urls will be fine:

`/refer/:repo/:user` => redirect to `/:repo/:user` but may choose different landing page in the future
`/:repo/:user/component-badge.png` => redirect to `/component-badge.png`
`/component-badge.png` => serve up the svg generated on demand by `component-badge`

To get the number of components for that, I suggest that you edit [get-components-list.js](https://github.com/ForbesLindesay/component-website/blob/master/get-components-list.js) to keep a count of how many there are and then simply use that. That way it gets updated every 15 minutes, which should be frequently enough.

**Comment by buschtoens** [comment]
Sounds great. I think I can spare another hour for implementing this. Let's hope to see a PR at dawn. :D

**Comment by buschtoens** [comment]
Will continue Monday afternoon (UTC). Had to do some other stuff.

**Comment by ForbesLindesay** [comment]
All done now.  As above but with `svg` not `png`.
